### ISSUE TITLE
Get data from store

### ISSUE THREAD

**Issue by LanceMango** [infinum/mobx-jsonapi-store#31]
Hey Darko,

my Name is Lance, I’m a developer from Germany and I’m using your mobx jsonapi store package.
I’m stuck in a problem and your documentation doesn’t help me anymore, so I felt free to write you.
I hope that’s ok for you. I would really appreciate to hear from you. So, what’s it all about?

I set up a store and synched it like this: 

```
const teststore = new Store();
const synched = {};
const fetchedData = fetch('http://localhost:3000/xxxxxxxxxxx',
    {
        method: 'GET',
        headers: {
            'xxxxxx': xxxxxxxxxx
        }
    })
    .then((response) =>
        response.json()
    )
    .then((json) => {
        Object.assign(synched, json.data);
    })
    .catch((error) =>
        console.log('Error while fetching events')
    );
    
const User = teststore.sync(synched);

console.log(User);
```

But at the bottom, the logged User is an empty Array. Why?
Can you help me with that?

I’m looking forward to hear from you!

**Comment by LanceMango** [comment]
Hi Lance,
Your code seems fine. Can you attach the response that doesn't work?

P.s. You could also use teststore.fetch or teststore.fetchAll to load the data directly into the store without using fetch and sync directly. This is not an issue here, just a suggestion.

**Comment by LanceMango** [comment]
hi darko,
that's my json response:

![bildschirmfoto 2017-05-21 um 13 14 18](https://cloud.githubusercontent.com/assets/3851397/26283390/f7f93544-3e27-11e7-9979-4966316463a9.png)

**Comment by DarkoKukovec** [comment]
Oh, I missed one thing when I initially looked at your code:
You're syncing the `synched` variable to the store right away, but it's still empty at that point. You need to call the `sync` method once the data was fetched from the server:

```javascript
const teststore = new Store();
const fetchedData = fetch('http://localhost:3000/xxxxxxxxxxx',
    {
        method: 'GET',
        headers: {
            'xxxxxx': xxxxxxxxxx
        }
    })
    .then((response) =>
        response.json()
    )
    .then((json) => {
        const User = teststore.sync(json.data);
        console.log(User);
    })
    .catch((error) =>
        console.log('Error while fetching events')
    );
```

Something with less boilerplate (`request` is a generic method, `fetchAll` or `fetch` might be better if you're doing regular fetching of the models):
```javascript
const teststore = new Store();

teststore.request('http://localhost:3000/xxxxxxxxxxx', 'GET', null, {
  headers: {'xxxxxx': 'xxxxxxxxxx'}
})
  .then((response) => {
    console.log(response.data); // User
  });
```

Or, if the headers are same every time:
```javascript
import {Store, config} from 'mobx-jsonapi-store';
const teststore = new Store();
config.defaultHeaders = {'xxxxxx': 'xxxxxxxxxx'};

teststore.request('http://localhost:3000/xxxxxxxxxxx')
  .then((response) => {
    console.log(response.data); // User
  });
```

Going a step further if you're inside of an [async function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function):
```javascript
import {Store, config} from 'mobx-jsonapi-store';
const teststore = new Store();
config.defaultHeaders = {'xxxxxx': 'xxxxxxxxxx'};

async function loadUser() {
  const response = await teststore.request('http://localhost:3000/xxxxxxxxxxx');
  console.log(response.data); // User
}
```

If' you're just fetching an user from https://example.com/user/1
```javascript
import {Store, config} from 'mobx-jsonapi-store';
const teststore = new Store();
config.defaultHeaders = {'xxxxxx': 'xxxxxxxxxx'};
config.baseUrl = 'https://example.com/';

async function loadUser() {
  const response = await teststore.fetch('user', 1);
  console.log(response.data); // User
}
```

I hope this helps :)
