### ISSUE TITLE
A way to set credentials property for requests

### ISSUE THREAD

**Issue by aldarund** [infinum/mobx-jsonapi-store#44]
I dont see a way how to set a credentials property of requests ( e.g. same-origin, include) 

https://fetch.spec.whatwg.org/#concept-request-credentials-mode

Am i missing something or its not possible with this lib? It should be set on each fetch call as i understand.

**Comment by DarkoKukovec** [comment]
This is correct - the only properties that can be set out-of-the-box are `method`, `body` and `headers`.

However, the [`config.baseFetch`](https://github.com/infinum/mobx-jsonapi-store/blob/master/src/NetworkUtils.ts#L60) method is exposed, and you can override it with another implementation. In your case, that might just be additional properties in `config.fetchReference` call.

It might make sense to expose some other properties in the future.

**Comment by aldarund** [comment]
@DarkoKukovec ye, but rewriting whole method to add 1 property doesnt sound like a good solution :) Ok, so thats the only option for now then i need to go that way

**Comment by fc-arny** [comment]
@aldarund I used axios for the same problem, see my example 

```
...
import { fetch } from 'app/core/utils/fetch';
config.baseUrl = '/api/';
config.baseFetch = fetch;
...
```

```
// app/core/utils/fetch.ts
import { IHeaders, IResponseHeaders, JsonApi } from 'mobx-jsonapi-store';
import axios, { AxiosResponse } from 'axios';

export const fetch = (method: string, url: string, body?: object, requestHeaders?: IHeaders) => {
    let data: JsonApi.IResponse;
    let status: number;
    let headers: IResponseHeaders;

    const request: Promise<void> = Promise.resolve();
    const uppercaseMethod: string = method.toUpperCase();

    return request
        .then(() => {
            return axios({
                url,
                method: uppercaseMethod,
                data: body,
                headers: requestHeaders,
            });
        })
        .then((response: AxiosResponse<any>) => {
            status = response.status;
            headers = response.headers;
            return response.data;
        })
        .catch((e: Error) => {
            if (status === 204) {
                return null;
            }
            throw e;
        })
        .then((responseData: JsonApi.IResponse) => {
            data = responseData;
            if (status >= 400) {
                throw {
                    message: `Invalid HTTP status: ${status}`,
                    status,
                };
            }

            return { data, headers, requestHeaders, status };
        })
        .catch((error) => {
            return { data, error, headers, requestHeaders, status };
        });
};
```

Or you are always could add support some thing like JWT and work without cookie :)

**Comment by DarkoKukovec** [comment]
Since version 4.2.0, this is possible by using the [`defaultFetchOptions`](https://github.com/infinum/mobx-jsonapi-store/wiki/config#defaultfetchoptions) config. cc @isBatak
