### ISSUE TITLE
Saving an existing model fails

### ISSUE THREAD

**Issue by andreicek** [infinum/mobx-jsonapi-store#56]
When saving a model that is in the collection the API call will go thru but the model will never get the new ID and an exception will be thrown.

I was able to fix the issue by modifying the `__getExternalRef` function in mobx-collection-store Model. I added a check if the collection is not defined on model to return an empty array.

```javascript
    Model.prototype.__getExternalRef = function (ref) {
        var _this = this;
        return mobx_1.computed(function () {
            return !_this.__collection ? [] : _this.__collection.findAll(ref.model)
                .filter(function (model) {
                var prop = model[ref.property];
                if (prop instanceof Array || mobx_1.isObservableArray(prop)) {
                    return prop.indexOf(_this) !== -1;
                }
                else {
                    return prop === _this;
                }
            });
        });
    };
```

**Comment by DarkoKukovec** [comment]
This was solved trough https://github.com/infinum/mobx-collection-store/pull/27
