### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by jtorreggiani** [infinum/mobx-jsonapi-store#78]
In the [Using the store](https://github.com/infinum/mobx-jsonapi-store/wiki/Using-the-store) section of the wiki, it provides the following instructions for removing models from the store.
```JavaScript
// Removing an exact model
collection.remove('person', 1);

// Remove all models of a certain type
collection.remove('person');
```
However, `collection.remove('person')` does not remove all the models, only the first one. 
I believe this should instead be `collection.removeAll('person')`.
https://github.com/infinum/mobx-jsonapi-store/blob/fdcfe533a1979f0d25bb935d00e2f360fc4d30b4/src/Store.ts#L162-L167

**Comment by DarkoKukovec** [comment]
You're right, thanks! Fixed.
