### ISSUE TITLE
Unsupported JSON-API features/roadmap

### ISSUE THREAD

**Issue by tristanpemble** [infinum/mobx-jsonapi-store#8]
This is a cool library. I am evaluating it for use in our greenfield React Native app. It would be useful to have a list of currently unimplemented, planned to be implemented JSON-API features, and some kind of roadmap. It may be that all features are supported (which would be pretty awesome), but before I dive in with code I'd like an idea of what functionality may be missing. Thanks!

**Comment by DarkoKukovec** [comment]
Hi @tristanpemble 

I created a list of all JSON API features that are available in the lib right now: https://github.com/infinum/mobx-jsonapi-store/blob/master/jsonapi.md
I also opened issues for all missing features: [Milestone](https://github.com/infinum/mobx-jsonapi-store/milestone/1)
I plan to address some of them in the following days.

If you want, you can make a list of deal-breakers and good-to-have missing features, and I'll try to prioritise them.

**Comment by tristanpemble** [comment]
That's fantastic, great work :)
